- name: Set sidebar icon size to medium
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: "{{ ui.sidebarIconSize }}"
    state: present

- name: Set Accent Color to orange
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleAccentColor
    type: int
    value: "{{ ui.accentColor }}"
    state: present

- name: Set Highlight Color also to orange
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleHighlightColor
    type: string
    value: "{{ ui.highlightColor }}"
    state: present

- name: Disable the over-the-top focus ring animation
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSUseAnimatedFocusRing
    type: bool
    value: false
    state: present

- name: Increase window resize speed for Cocoa applications
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSWindowResizeTime
    type: float
    value: "{{ ui.resizeTime }}"
    state: present


- name: Automatically quit printer app once the print jobs complete
  community.general.osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

- name: Disable the “Are you sure you want to open this application?” dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
    state: present

- name: Display ASCII control characters using caret notation in standard text views
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTextShowsControlCharacters
    type: bool
    value: true
    state: present

- name: Disable automatic termination of inactive apps
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSDisableAutomaticTermination
    type: bool
    value: true
    state: present

- name: Set Help Viewer windows to non-floating mode
  community.general.osx_defaults:
    domain: com.apple.helpviewer
    key: DevMode
    type: bool
    value: true
    state: present

- name: Disable anoying autocorrect
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item }}"
    type: bool
    value: false
    state: present
  with_items:
    - NSAutomaticDashSubstitutionEnabled
    - NSAutomaticPeriodSubstitutionEnabled
    - NSAutomaticQuoteSubstitutionEnabled
