###############################################################################
# Screen                                                                      #
###############################################################################

- name: Require password after sleep or screen saver
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: "{{ '1' if energy.screensaver.askForPassword else '0' }}"
    state: present

- name: Require password immediately after sleep or screen saver begins
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: "{{ energy.screensaver.passwordDelay }}"
    state: present

- name: Save screenshots to the desktop
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ screenshots.location }}"
    state: present

- name: "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: "{{ screenshots.format }}"
    state: present

- name: Disable shadow in screenshots
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: "{{ screenshots.disableShadow }}"
    state: present

# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
- name: Enable subpixel font rendering on non-Apple LCDs
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    type: int
    value: 1
    state: present

- name: Enable HiDPI display modes (requires restart)
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.windowserver
    key: DisplayResolutionEnabled
    type: bool
    value: true
    state: present
  become: true
