#!/usr/bin/env zsh

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.config/{path,zinit,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
setopt CSH_NULL_GLOB;

# Append to the Bash history file, rather than overwriting it
setopt APPEND_HISTORY;

# Autocorrect typos in path names when using `cd`
#shopt -s cdspell;
