- name: Enable the automatic update check
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: true
    state: present

- name: Check for software updates daily, not just once per week
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1
    state: present

- name: Download newly available updates in background
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: int
    value: 1
    state: present

- name: Install System data files & security updates
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: int
    value: 1
    state: present

- name: Automatically download apps purchased on other Macs
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ConfigDataInstall
    type: int
    value: 1
    state: present

- name: Turn on app auto-update
  community.general.osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdate
    type: bool
    value: true
    state: present

- name: Allow the App Store to reboot machine on macOS updates
  community.general.osx_defaults:
    domain: com.apple.commerce
    key: AutoUpdateRestartRequired
    type: bool
    value: true
    state: present
