
- name: Prevent Photos from opening automatically when devices are plugged in
  community.general.osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    host: current
    type: bool
    value: true
    state: present


- name: Download And keep originals on mac
  community.general.osx_defaults:
    domain: com.apple.photos.shareddefaults
    key: downloadAndKeepOriginals
    type: bool
    value: true
    state: present
