# Installing Docker
cask "docker"

brew "mas" # Appstore CLI

# Important for playbooks
brew "chezmoi" # Chezmoi for syncing dotfiles
brew "dockutil"

# Installing core commands
brew "git"
brew "grep"
brew "gnutls"
brew "gnupg"
brew "git-lfs"
brew "screen"
brew "tree"
brew "findutils"
brew "coreutils"
brew "moreutils"
brew "foremost"
brew "netcat"
brew "wget"
brew "curl"

cask "arc" # Arc Browser
cask "grandperspective" # GrandPerspective
cask "1password" # 1Password
cask "1password-cli"

# Productivity
cask "notion"
cask "webex"
cask "lm-studio"
cask "zotero"


# Microsoft Office
cask "microsoft-auto-update"
cask "microsoft-word"
cask "microsoft-excel"
cask "microsoft-powerpoint"
mas "Goodnotes", id: 1444383602
mas "Keynote", id: 409183694

cask "postman" # Postman
cask "intellij-idea"
cask "android-studio"
brew "kotlin"
brew "kdoctor"
brew "cocoapods"
brew "cmake"
brew "nvm"
brew "openjdk@17"
brew "go"
brew "python@3.11"
mas "Xcode", id: 497799835
brew "swiftlint"

# Zed Editor
cask "zed"

# Visual Studio Code
cask "visual-studio-code"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "golang.go"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
