- name: Setup Mac
  hosts: localhost
  roles:
    - role: check-become
    - role: macos-defaults
      defaults_path: "../macos-defaults"
    - role: dock_setup
      apps:
        - "file:///Applications/Arc.app"
        - "file:///System/Applications/Calendar.app"
        - "file:///System/Applications/Reminders.app"
        - "file:///System/Applications/Notes.app/"
        - "file:///Applications/Goodnotes.app"
        - "file:///System/Applications/Utilities/Terminal.app"
      folders:
        - name: "file:///{{ lookup('env', 'HOME') }}/Documents/"
          view: "list" # grid|fan|list|auto
          display: "folder" # folder|stack
          sort: "datemodified" # name|dateadded|datemodified|datecreated|kind
        - name: "file:///{{ lookup('env', 'HOME') }}/Downloads/"
          view: "fan" # grid|fan|list|auto
          display: "stack" # folder|stack
          sort: "dateadded" # name|dateadded|datemodified|datecreated|kind
