- name: Setup Mac
  hosts: localhost
  tasks:
    - include_tasks: tasks/check-become.yaml
    - include_tasks: tasks/macos-defaults.yaml
      vars:
        defaults_path: "../macos-defaults"
    - include_tasks: tasks/dock-setup.yaml
      vars:
        apps:
          - "file:///Applications/Arc.app"
          - "file:///System/Applications/Calendar.app"
          - "file:///System/Applications/Reminders.app"
          - "file:///System/Applications/Notes.app/"
          - "file:///Applications/Goodnotes.app"
          - "file:///System/Applications/Utilities/Terminal.app"
        folders:
          - name: "file:///{{ lookup('env', 'HOME') }}/Documents/"
            view: "list" # grid|fan|list|auto
            display: "folder" # folder|stack
            sort: "datemodified" # name|dateadded|datemodified|datecreated|kind
          - name: "file:///{{ lookup('env', 'HOME') }}/Downloads/"
            view: "fan" # grid|fan|list|auto
            display: "stack" # folder|stack
            sort: "dateadded" # name|dateadded|datemodified|datecreated|kind
    - include_tasks: tasks/power-management.yaml
      vars:
        energy:
          displaySleepAfter: 15
          sleepAfter: 2
          disableSleepOnCharge: true
          standbyDelay: 24 # Hours
          disableSleepMode: true
    - include_tasks: tasks/restart-mac.yaml
      vars:
        message: "Do you want to restart now to apply all changes?"
